version: '3'
services:
  go-upload-progress:
    build: .
    environment:
      SERVER_ADDRESS: ':8080'
      PUBLIC_FILE_DIR: '/opt/go-upload-progress/public'
      UPLOADED_FILE_DIR: '/opt/go-upload-progress/files'
    ports:
      - 8080:8080
    volumes:
      - ./files:/opt/go-upload-progress/files
    restart: always

  swagger:
    image: swaggerapi/swagger-ui:v4.15.5
    environment:
      SWAGGER_JSON: /opt/go-upload-progress/swagger.yaml
    ports:
      - 9090:8080
    volumes:
      - ./docs/swagger.yaml:/opt/go-upload-progress/swagger.yaml:ro
    restart: always

  jsdoc:
    build:
      context: .
      dockerfile: Dockerfile.jsdoc
    ports:
      - 9091:80
    restart: always
